export const SHOW_MODAL = "SHOW_MODAL"
export const NAME ="Muhammad Zohaib"
export const USERNAME = "@zohaibkhan"
export const TEXT = "This Person reacted to your post"
export const TIME = "About an hour ago"
export const LOCATION = "Location"
export const LOC_DESP ="Show content in this location"
export const LOC_PARA= " When this is on, you’ll see what’s happening around you right now."
export const TREND = "Trends for you"
export const SHOW_MORE= "Show More"
export const HAPEENING_NOW = "Happening Now"
export const JOIN_TWITTER_TODAY = "Join Twitter Today"
export const TERMS= "Terms of Service"
export const PRIVACY = "Privacy Policy"
export const COOKIE = "Cookie Use"
export const ALREADY_ACC= "Already have an account?"
export const LOGOUT = "Log out of Twitter?"
export const LOGOUT_PARA = "You can always log back in at any time. If you just want to switch accounts, you can do that by adding an existing account."
export const CREATE_ACC= "Create Your Account"
export const SIGNUP_PARA= "This will not be shown publicly. Confirm your own age, even if this account is for a business, a pet, or something else."
export const DOB = "Date of birth"
export const SIGN_IN ="Sign in to Twitter"


